spring:
  application:
    name: hystrix
    
server:
  port: 3001
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka
      
ribbon:
  MaxAutoRetriesNextServer: 2   #更换实例的次数
  MaxAutoRetries: 1   #当前实例重试次数，尝试失败会更换下一个实例
  OkToRetryOnAllOperations: true    #对连接超时、读取超时都进行重试


#hystrix 等待超时  
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 500
 

#监控信息的监控端点
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream 